# Generated by Django 5.0.4 on 2024-06-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwords',
            options={'verbose_name_plural': 'Passwords'},
        ),
    ]
