# Generated by Django 5.0.4 on 2024-06-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_passwords_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='vault_name',
            field=models.CharField(max_length=255),
        ),
    ]
