# Generated by Django 5.0.4 on 2024-06-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_customuser_alter_passwords_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vault', to='manager.customuser'),
        ),
    ]
